version: '3.3'
services:
  demo_management:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - "8000:8080"
    restart: always
    container_name: demo_management
    image: demo_management:1.0
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo